### ISSUE TITLE
Try to write a script to add a mirror of the repository.

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#37]
I am trying to create a script written in python to conveniently use the mirroring of this repository. The reason why I don't write scripts in bash is because I am not familiar with bash.

**Comment by chunky-milk** [comment]
Good idea. I don't have any knowledge in Python just so you know, but feel free to send a PR when you create a script that works

**Comment by Itai-Nelken** [comment]
I think that python might actually be better than bash if we need to detect users location because there are more api's available for python to do things like this. We will still need to use a bash script to run the python one though to make things simpler unless you can pipe a python script to python.

**Comment by hmsjy2017** [comment]
Finished at #71 .
